ptbr = [
  "como você tá hoje?",
  "já deu chupão em alguém?",
  "já traiu, tem que ser honesto kkk",
  "quais são as maiores red flags em um cara?",
  "qual é a casa dos seus sonhos?",
  "trabalho dos sonhos?",
  "isso é verdade?",
  "tô apaixonado por vc",
  "você é fofa",
  "qual é sua banda favorita?",
  "quem foi o último cara com quem você mandou mensagem?",
  "o pior encontro que você já teve?",
  "snap?",
  "vamos transar?",
  "para de me deixar no vácuo",
  "tenho chance c vc?",
  "me mostra seus pés?",
  "quantos anos você tem mesmo?",
  "eu quero muito te comer",
  "eu quero muito te chupar",
  "eu sei o que você fez",
  "você é feio pra krl kkkkkkkkk",
  "a gente pode ser melhores amigos?",
  "de onde você é?",
  "netflix e chill? ou talvez um sexo bolado",
  "você é gostosa pra caralho",
  "queria ser seu travesseiro todas as noites",
  "seu sorriso é surreal",
  "tô só esperando pra te beijar",
  "você é lind d+",
  "posso te beijar?",
  "cu",
  "seus olhos dizem tudo o que preciso saber.",
  "queria poder te abraçar para sempre.",
  "você é a melhor parte dos meus sonhos",
  "vc é minha droga favorita.",
  "você me deixa sem fôlego",
  "não consigo parar de pensar em você",
  "quando você sorri o mundo para",
  "quero ser seu melhor momento do dia",
  "seu cheiro me enlouquece",
  "sua voz é música para os meus ouvidos",
  "você é meu vício mais saudável",
  "me perdi em seus olhos",
  "queria poder te abraçar agora mesmo",
  "seu beijo é minha fraqueza",
  "você é o motivo do meu sorriso",
  "to pronto p fazer sapecage",
  "seu corpo é uma obra de arte",
  "quero beijar cada pedaço de vc",
  "cola aqui em casa",
  "você é a fantasia que nunca soube que tinha",
  "quero que este momento dure para sempre.",
  "sexooooooooooooo",
  "sempre gostei de vc",
  "voce lembra daquela vez?",
  "seu sorriso é meu raio de sol",
  "um dia a gnt se encontra",
  "a",
  "sua namorada ta ai?",
  "vc lembra da nossa ultima vez?",
  "com você ou sem você, fodase",
  "seu abraço é mto bom"
]

en = [
  "how are you today?",
  "have you ever given a hickey?",
  "have you ever cheated, you gotta be honest lol",
  "biggest red flags in a guy?",
  "what's your dream house?",
  "dream job?",
  "is it true?",
  "i have a crush on u",
  "you're cute",
  "what's your fav band?",
  "who was the last dude you texted?",
  "the worst date you've ever been on?",
  "snap?",
  "lets fuck?",
  "yo stop leaving me on read",
  "ain't no way",
  "show me your feet?",
  "how old are you again?",
  "i wanna fuck u so bad",
  "i wanna suck you so bad",
  "i know what u did",
  "u ugly af",
  "can we be besties?",
  "where are you from?",
  "netflix and chill? or maybe sex",
  "you're a walking temptation.",
  "i wish i could be your pillow every night.",
  "your smile is my aphrodisiac.",
  "i'm just waiting for the green light to kiss you.",
  "you're so hot, you melt the ice.",
  "can i steal a kiss from you?",
  "you're the definition of irresistible.",
  "your eyes tell me everything i need to know.",
  "i wish i could hug you forever.",
  "you're the best part of my dreams.",
  "your touch is my favorite drug.",
  "you leave me breathless.",
  "i can't stop thinking about you.",
  "let's make tonight unforgettable.",
  "when you smile, the world stops.",
  "i want to be your favorite part of the day.",
  "your scent drives me wild.",
  "your voice is music to my ears.",
  "you're my healthiest addiction.",
  "i'm lost in your eyes.",
  "i wish i could hug you right now.",
  "your kiss is my weakness.",
  "you're the reason for my smile.",
  "together, we can conquer the world.",
  "i'm ready to get lost with you.",
  "your body is a work of art.",
  "i want to explore you slowly.",
  "let's get lost in the sheets together.",
  "you're the fantasy i never knew i had.",
  "i wish this moment could last forever.",
  "your lips are like magnets to mine.",
  "you're everything i've ever wanted.",
  "i wish tonight would never end.",
  "your smile is my sunshine.",
  "you make me believe in fairy tales.",
  "i'm completely surrendered to you.",
  "you're my favorite place.",
  "let's make tonight an unforgettable memory.",
  "with you, i feel complete.",
  "your hug is my safe haven.",
  "there's no place i'd rather be than by your side.",
  "i want to get lost in your arms forever.",
  "you're my downfall and my salvation.",
  "every second with you is a gift.",
  "i'm completely in love with you.",
  "you're the best part of my day.",
  "i want to make you feel special.",
  "you're my deepest desire.",
  "with you, i feel alive.",
  "let's make this moment last forever."
];
